services:
  postgres:
    extends:
      file: ../database/docker-compose.yaml
      service: postgres

  adminer:
    extends:
      file: ../database/docker-compose.yaml
      service: adminer

  leo-planer:
    build:
      context: ../leo-planer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/demo
      QUARKUS_DATASOURCE_USERNAME: demo
      QUARKUS_DATASOURCE_PASSWORD: demo
      QUARKUS_HTTP_HOST: 0.0.0.0
    volumes:
      - ../leo-planer:/workspace
      - m2-cache:/root/.m2
    command: ["mvn", "quarkus:dev", "-Dquarkus.http.host=0.0.0.0", "-Ddebug=false"]

volumes:
  postgres:
  m2-cache: