services:
  postgres:
    extends:
      file: ../database/docker-compose.yaml
      service: postgres

  adminer:
    extends:
      file: ../database/docker-compose.yaml
      service: adminer
      
  leo-planer:
    build:
      context: ../leo-planer
      dockerfile: Dockerfile 
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/demo


volumes:
  postgres: